# Generated by Django 3.0 on 2021-05-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20210520_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='etudiant',
            field=models.BooleanField(default=True, verbose_name="Ancien étudiant de l'ENSGSI "),
        ),
        migrations.AlterField(
            model_name='student',
            name='annee',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Si oui année de l'obtention du diplôme "),
        ),
        migrations.AlterField(
            model_name='student',
            name='formation_1',
            field=models.BooleanField(default=False, verbose_name="Je souhaite également m'inscrire le 29 Juin à la formation payante "),
        ),
        migrations.AlterField(
            model_name='student',
            name='formation_2',
            field=models.BooleanField(default=False, verbose_name="Je souhaite également m'inscrire le 30 Juin à la formation payante "),
        ),
        migrations.AlterField(
            model_name='student',
            name='niveau_etude',
            field=models.CharField(default=True, max_length=100, verbose_name="Niveau d'étude "),
        ),
    ]
